server.port: 8083
application.id.config: ms-pacote

spring:
  application.name: ms-pacote
  kafka:
    bootstrap-servers: localhost:9092
    group_id: ms-pacote
    auto-offset-reset: earliest
    
topico:
   voos_selecionados.nome: voos.selecionados
   hospedagens_selecionadas.nome: hospedagens.selecionadas
   pacotes_criados.nome: pacotes
